"""adding new column cateogry migrate

Revision ID: 7b9bf0049cf0
Revises: 10dc73c1a355
Create Date: 2024-08-16 22:54:53.063869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9bf0049cf0'
down_revision = '10dc73c1a355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
